src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private ?string $imdb;

    /**
     * @ORM\Column(type="datetimetz", nullable="true")
     * @Assert\DateTime()
     */
    private ?\DateTimeInterface $startTime;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $runtime = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rating", mappedBy="movie", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $ratings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="movie", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank
     */
    private ?int $yearFeasted;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $curatorComment;

    public function __construct()
    {
        $this->ratings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title ?? 'Untitled';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImdb(): ?string
    {
        return $this->imdb;
    }

    public function setImdb(?string $imdb): self
    {
        $this->imdb = $imdb;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(?\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getRuntime(): ?int
    {
        return $this->runtime;
    }

    public function setRuntime(?int $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setMovie($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getMovie() === $this) {
                $rating->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setMovie($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getMovie() === $this) {
                $comment->setMovie(null);
            }
        }

        return $this;
    }

    public function getAverageRating(): float|int
    {
        if (sizeof($this->ratings) === 0)
            return 0;

        $total = array_reduce($this->ratings->toArray(), function($carry, Rating $rating) {
            return $carry + $rating->getScore();
        }, 0);

        return round($total / sizeof($this->ratings), 1);
    }

    public function isMovieActive(): bool
    {
        if (!$this->startTime)
            return false;

        $now = new \DateTime('now');
        $isAfterStartTime = $now->getTimestamp() > $this->getStartTime()->getTimestamp();
        $endTime = $this->getEndTime();
        $isBeforeRuntime = $now->getTimestamp() < $endTime->getTimestamp();
        return $isAfterStartTime && $isBeforeRuntime;
    }

    public function isMovieOver(): bool
    {
        if (!$this->startTime)
            return true;

        $now = new \DateTime('now');
        return $now->getTimestamp() > $this->getEndTime()->getTimestamp();
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        if (!$this->startTime)
            return null;

        $endTime = clone $this->getStartTime();
        $endTime->modify($this->getRuntime() . ' minutes');
        return $endTime;
    }

    public function getYearFeasted(): ?int
    {
        return $this->yearFeasted;
    }

    public function setYearFeasted(?int $yearFeasted): self
    {
        $this->yearFeasted = $yearFeasted;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function isReadOnly(): bool
    {
        if (!$this->startTime)
            return true;

        $now = new \DateTime('now');

        $interval = $this->startTime->diff($now);

        return $interval->days > 14;
    }

    public function isSecret(): bool
    {
        $now = new \DateTime('now');

        return $this->startTime > $now;
    }

    public function getCuratorComment(): ?string
    {
        return $this->curatorComment;
    }

    public function setCuratorComment(?string $curatorComment): self
    {
        $this->curatorComment = $curatorComment;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\OMDB\API;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(MovieRepository $movieRepository)
    {
        $year = (int)(new \DateTime('now'))->format('Y');

        $movies = $movieRepository->findBy(
            [
                'yearFeasted' => $year,
            ],
            [
                'startTime' => 'ASC',
            ]
        );




        return $this->render('home/index.html.twig', [
            'title' => "Travis Wayne Hurt International Film Festival 2025",
            'description' => null,
            'movies' => $movies,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block head %}
    <meta property="og:title" name="og:title" content="{{ title }}" />
    {% if description %}
        <meta property="og:description" name="og:description" content="{{ description }}" />
    {% endif %}
    <meta property="og:type" name="og:type" content="article" />
    <meta property="og:url" name="og:url" content="{{ app.request.uri }}" />
    <meta property="og:image" name="og:image" content="{{ asset('images/twh.webp') }}" />
    <meta property="twitter:card" name="twitter:card" content="summary_large_image" />
    <meta property="og:locale" name="og:locale" content="en_US" />
{% endblock %}

{% block body %}
    <main>
        <div class="jumbotron jumbotron-fluid bg-travis-yellow">
            <div class="container">
                <h1 class="display-4 text-center mb-3 text-travis-red">{{ title }}</h1>
                <div class="list-group">
                    {% for movie in movies %}
                        <a class="list-group-item list-group-item-action {{ movie.movieOver ? 'list-group-item-light' }} bg-light text-travis-red"
                           style="display: flex; align-items: center;"
                           href="{{ path('movie_details', {movie:movie.id}) }}">
                            {{ movie.startTime|date('M j, g:i A') }} – {{ movie.secret ? "SECRET" : movie.title }}
                            {% if movie.movieOver %}
                                <span style="margin-left: auto" class="fa fa-check"></span>
                            {% endif %}
                            {% if movie.movieActive %}
                                <span style="margin-left: auto" class="fa fa-play"></span>
                            {% endif %}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="container">
            <ul class="p-0">
                {% for movie in movies %}
                    <li class="row" style="margin-bottom: 24px;">
                        <div class="col-sm-3">
                            <a href="{{ path('movie_details', {movie:movie.id}) }}">
                                <img class="img-fluid" src="{{ movie.secret ? "https://placehold.co/300x446?text=SECRET" : omdb.getPosterURL(movie.imdb) }}" alt="" role="presentation">
                            </a>
                        </div>
                        <div class="col-sm-9">
                            <p>
                                <strong>
                                    Starting at {{ movie.startTime|date('g:i A') }}
                                </strong>
                            </p>
                            <div style="margin-bottom: 16px;">
                                <h2 style="display:inline;">
                                    <a href="{{ path('movie_details', { 'movie': movie.id }) }}">
                                        {{ movie.secret ? "SECRET" : movie.title }}
                                    </a>
                                </h2>
                                {% if not movie.secret %}
                                    <span>
                                        <a href="https://imdb.com/title/{{ movie.imdb }}" target="_blank" rel="noopener">
                                            (IMDb <span class="fa fa-external-link-alt"></span>)
                                        </a>
                                    </span>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    {% include 'partials/movie-people.html.twig' %}
                                </div>
                                <div class="col-sm-4">
                                    {% include 'partials/movie-info.html.twig' %}
                                </div>
                                <div class="col-sm-4">
                                    <dl>
                                        <dt>Average Rating</dt>
                                        <dd>
                                            {% include 'partials/average-rating.html.twig' %}
                                        </dd>
                                        <dt>
                                            Comments
                                        </dt>
                                        <dd>
                                            {% include 'partials/comments-count.html.twig' %}
                                        </dd>
                                        {% if movie.curatorComment %}
                                            <button class="bit-button" type="button" data-toggle="modal" data-target="#modal-{{ movie.id }}">
                                                <img src="{{ asset('images/twh.webp') }}" width="25" height="32">
                                            </button>
                                            {% include 'partials/modal.html.twig' %}
                                        {% endif %}
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <p>No movies scheduled yet.</p>
                {% endfor %}
            </ul>
        </div>
    </main>
{% endblock %}