src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private ?string $imdb;

    /**
     * @ORM\Column(type="datetimetz", nullable="true")
     * @Assert\DateTime()
     */
    private ?\DateTimeInterface $startTime;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $runtime = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rating", mappedBy="movie", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $ratings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="movie", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank
     */
    private ?int $yearFeasted;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $curatorComment;

    public function __construct()
    {
        $this->ratings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title ?? 'Untitled';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImdb(): ?string
    {
        return $this->imdb;
    }

    public function setImdb(?string $imdb): self
    {
        $this->imdb = $imdb;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(?\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getRuntime(): ?int
    {
        return $this->runtime;
    }

    public function setRuntime(?int $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setMovie($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getMovie() === $this) {
                $rating->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setMovie($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getMovie() === $this) {
                $comment->setMovie(null);
            }
        }

        return $this;
    }

    public function getAverageRating(): float|int
    {
        if (sizeof($this->ratings) === 0)
            return 0;

        $total = array_reduce($this->ratings->toArray(), function($carry, Rating $rating) {
            return $carry + $rating->getScore();
        }, 0);

        return round($total / sizeof($this->ratings), 1);
    }

    public function isMovieActive(): bool
    {
        if (!$this->startTime)
            return false;

        $now = new \DateTime('now');
        $isAfterStartTime = $now->getTimestamp() > $this->getStartTime()->getTimestamp();
        $endTime = $this->getEndTime();
        $isBeforeRuntime = $now->getTimestamp() < $endTime->getTimestamp();
        return $isAfterStartTime && $isBeforeRuntime;
    }

    public function isMovieOver(): bool
    {
        if (!$this->startTime)
            return true;

        $now = new \DateTime('now');
        return $now->getTimestamp() > $this->getEndTime()->getTimestamp();
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        if (!$this->startTime)
            return null;

        $endTime = clone $this->getStartTime();
        $endTime->modify($this->getRuntime() . ' minutes');
        return $endTime;
    }

    public function getYearFeasted(): ?int
    {
        return $this->yearFeasted;
    }

    public function setYearFeasted(?int $yearFeasted): self
    {
        $this->yearFeasted = $yearFeasted;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function isReadOnly(): bool
    {
        if (!$this->startTime)
            return true;

        $now = new \DateTime('now');

        $interval = $this->startTime->diff($now);

        return $interval->days > 14;
    }

    public function isSecret(): bool
    {
        $now = new \DateTime('now');

        return $this->startTime > $now;
    }

    public function getCuratorComment(): ?string
    {
        return $this->curatorComment;
    }

    public function setCuratorComment(?string $curatorComment): self
    {
        $this->curatorComment = $curatorComment;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Travis Wayne Hurt International Movie Festival{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('bootstrap-4.6.0-dist/css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ asset('fontawesome-free-5.11.2-web/css/all.min.css') }}">
            <link rel="stylesheet" href="{{ asset('custom.css') }}">
        {% endblock %}

        <link rel="icon" type="image/png" href="/favicon.png">

        {% block head %}
        {% endblock %}
    </head>
    <body class="text-black">
        <header>
            {% if app.session %}
                <div class="container">
                    <div class="row">
                        <div class="col-sm">
                            {% for error in app.session.flashBag.get('error') %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                            {% endfor %}

                            {% for notice in app.session.flashBag.get('notice') %}
                                <div class="alert alert-success">
                                    {{ notice }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </header>
        {% block body %}
            <main class="container">
                {% block container %}
                {% endblock %}
            </main>
        {% endblock %}
        {% block javascripts %}
            <script src="{{ asset('js/jquery-3.x-git.slim.js') }}"></script>
            <script src="{{ asset('bootstrap-4.6.0-dist/js/bootstrap.bundle.min.js') }}"></script>
        {% endblock %}
    </body>
</html>

templates/movie.html.twig
{% extends 'base.html.twig' %}

{% import 'partials/stars.html.twig' as stars %}

{% block title %}{{ movie.secret ? "SECRET" : movie.title }}{% endblock %}

{% block body %}
    <main class="container">
        <div class="row mb-4">
            <div class="col-sm">
                <p><a href="{{ path('home') }}">Back home</a></p>
                {% include 'partials/movie-title-with-imdb.html.twig' %}
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-sm">
                <button
                    type="button" class="btn btn-lg btn-travis-red"
                    data-toggle="popover"
                    data-bs-placement="bottom"
                    title="Genre & plot"
                    data-placement="bottom"
                    data-content="{{ movie.secret ? "SECRET" : omdb(movie).Genre }}. {{ movie.secret ? "SECRET" : omdb(movie).Plot }}."
                >
                    Reveal plot
                </button>
            </div>
        </div>

        <div class="row">
            <div class="col-sm">
                <p>
                    <img class="img-fluid" src="{{ movie.secret ? "https://placehold.co/300x446?text=SECRET" : omdb.getPosterURL(movie.imdb) }}" alt="{{ movie.title }}">
                </p>
            </div>
            <div class="col-sm">
                {% include 'partials/movie-people.html.twig' %}
            </div>
            <div class="col-sm">
                {% include 'partials/movie-info.html.twig' %}
            </div>
            <div class="col-sm">
                <h2>Average Rating</h2>
                    {% if movie.ratings|length > 0 %}
                        <p class="display-3" style="display: flex; align-items: center;">
                            {{ movie.averageRating }}
                            <span style="font-size: 0.5em; margin-left: 0.5em;">
                                {{ stars.stars(movie.averageRating) }}
                            </span>
                        </p>
                    {% else %}
                        <p>No ratings yet!</p>
                    {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-sm">
                <h2>Ratings</h2>

                <ul class="list-group">
                    {% for rating in movie.ratings %}
                        <li class="list-group-item">
                            {{ stars.stars(rating.score) }} by <strong>{{ rating.rater }}</strong>
                        </li>
                    {% else %}
                        <li class="list-group-item">No ratings yet!</li>
                    {% endfor %}
                </ul>

                {% if not readOnly %}
                    <hr>

                    <h3>Submit a rating</h3>

                    {{ form_start(ratingForm) }}
                    {{ form_widget(ratingForm) }}
                    <p>
                        <button class="btn btn-travis-red" type="submit" formnovalidate>Submit</button>
                    </p>
                    {{ form_end(ratingForm) }}
                {% endif %}
            </div>

            <div class="col-sm">
                <h2>Comments</h2>

                {% if comments %}
                    {% for comment in comments %}
                        {% include 'partials/comment.html.twig' %}
                    {% endfor %}
                    <div>
                        <a href="{{ path('movie_comments', {movie:movie.id}) }}">See all comments ({{ movie.comments|length }})</a>
                    </div>
                {% else %}
                    <p>No comments yet!</p>
                {% endif %}

                {% if not readOnly %}
                    <hr>

                    <h3>Submit a comment</h3>

                    {{ form_start(commentForm) }}
                    {{ form_widget(commentForm) }}
                    <p>
                        <button class="btn btn-travis-red" type="submit" formnovalidate>Submit</button>
                    </p>
                    {{ form_end(commentForm) }}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col col-md-6">
                <h2>TWH says:</h2>
                <div>{{ movie.secret ? "SECRET" : movie.curatorComment|raw }}</div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm">
                <p>
                    <a href="{{ path('home') }}">Back home</a>
                </p>
            </div>
        </div>
    </main>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    {{ parent() }}
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })
    </script>
{% endblock %}

templates/rating_widget.html.twig
{% block rating_score_widget %}
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="5.0">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="4.5">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star-half"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="4.0">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="3.5">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star-half"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="3.0">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="2.5">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star-half"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="2.0">
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="1.5">
            <span class="fa fa-star"></span>
            <span class="fa fa-star-half"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="1.0">
            <span class="fa fa-star"></span>
        </label>
    </div>
    <div class="form-check">
        <label>
            <input type="radio" name="{{ full_name }}" value="0.5">
            <span class="fa fa-star-half"></span>
        </label>
    </div>
{% endblock %}